### ISSUE TITLE
请问关于”存入数据库失败“

### ISSUE THREAD

**Issue by liangzhdp** [zchan0/KindleNote#1]
为什么上传My clippings.txt文件会出现”存入数据库失败“，怎么处理？

**Comment by zchan0** [comment]
@liangzhdp  数据库创建了吗？还有对应的字段名是否和代码里的一致？repo里忘记上传SQL文件了＝＝

**Comment by liangzhdp** [comment]
@zchan0 空间原有数据库的，安装其他网站程序都可以，不过那些网站程序是有个向导填写数据库名、密码什么的。这里是那个文件对应是干这活的？烦请说明一下。

**Comment by zchan0** [comment]
@liangzhdp 
func.php里面有连接到数据库的配置，
`$db = new mysqli('localhost', 'root', '1a2b', 'KindleNote');`
你需要新建一个数据库，root, 1a2b, KindleNote，对应用户名，密码及数据库名
然后还需要两个表, file和note，具体有哪些字段我不记得了，你可以参考代码，有空的时候我会补上sql。
如果你仅是需要这个功能，用这个[网站](https://www.clippings.io/)就好

**Comment by liangzhdp** [comment]
谢谢，那就用现成的好了。
